export const GET_TOTAL_REVENUE = 'GET_TOTAL_REVENUE'
export const GET_TOTAL_REVENUE_FAILED = ' GET_TOTAL_REVENUE_FAILED '
export const GET_TOTAL_REVENUE_COMPLETED = 'GET_TOTAL_REVENUE_COMPLETED'

export const GET_TOTAL_ADMIN_FEES = 'GET_TOTAL_ADMIN_FEES'
export const GET_TOTAL_ADMIN_FEES_FAILED = 'GET_TOTAL_ADMIN_FEES_FAILED'
export const GET_TOTAL_ADMIN_FEES_COMPLETED = 'GET_TOTAL_ADMIN_FEES_COMPLETED'

export const GET_TOTAL_JOBS = 'GET_TOTAL_JOBS'
export const GET_TOTAL_JOBS_FAILED = 'GET_TOTAL_JOBS_FAILED'
export const GET_TOTAL_JOBS_COMPLETED = 'GET_TOTAL_JOBS_COMPLETED'
