const Message = {
    ERRORMESSAGE: {
        EMPTYFIELD: "This field cannot be empty.",
        EMAILEMPTY: 'This field cannot be empty.',
        OLDEMPTY: 'Old password cannot be empty',
        INVALIDOTP: 'OTP contains only numeric value',
        OTPEMPTY: 'OTP cannot be empty',
        CONTACTEMPTY: 'Contact number cannot be empty',
        EMAILINVALID: 'Are you sure you have entered a valid email address?',
        PASSWORDEMPTY: 'This field cannot be empty.',
        FIRSTNAMEEMPTY: 'This field cannot be empty.',
        FULLNAMEEMPTY: 'Full name cannot be empty.',
        MESSAGEEMPTY: 'Message cannot be empty.',
        SUBJECTEMPTY: 'Subject cannot be empty.',
        DESPEMPTY: 'Subject cannot be empty.',
        DISPUTEEMPTY: 'Dispute reason can’t be empty.',
        TITLEEMPTY: 'Title cannot be empty.',
        AMOUNTEMPTY: 'Amount cannot be empty.',
        AMOUNTVALID: 'This field can only contain "Numeric” values, “Decimal” value and “Decimal symbol" Please try again.',
        JOBTITLEEEMPTY: 'Job title cannot be empty.',
        JOBDESPEEMPTY: 'Job description can’t be empty.',
        JOBFOREMPTY: 'Job for can’t be empty.',
        MILESTONEEMPTY: 'Milestone  can’t be empty.',
        NATIONALITYEMPTY: 'Nationality cannot be empty.',
        ORGANISATIONEMPTY: 'Business name cannot be empty.',
        BUSINESSNAMEEMPTY: 'This field cannot be empty.',
        LASTNAMEEMPTY: 'This field cannot be empty.',
        ALFANUMINVALID: 'This field cannot contain special characters.',
        ALFAVALID: 'Allow only alphabetic value',
        ONLYALFAVALID: 'This field can only contain "Alphanumeric" values. Please try again. ',
        NEWPASSOWRD: 'password cannot be empty.',
        CONFIRMPASSWORD: 'This field cannot be empty.',
        CONFIRMINVALID: 'Both passwords must match. ',
        MAXEMPTY: 'Amount can’t be empty',
        MINEMPTY: 'Amount can’t be empty',
        MININVALID: 'Only contain numeric values',
        MAXINVALID: 'Only contain numeric values',
        ACCOUNTNUMBEREMPTY: 'This field cannot be empty.',
        SORTCODEEMPTY: 'This field cannot be empty.',
        SORTCODEVAILID: 'Please enter "numeric" values only.',
        COMPANYNAMEEMPTY: 'This field cannot be empty.',
        COMPANYNUMBEREMPTY: 'Company Number cannot be empty.',
        TRANSACTIONNAMEEMPTY: 'Transaction details cannot be empty.',
        DESPEEMPTY: 'Description can’t be empty.',
        HOUSENAMEEMPTY: 'This field cannot be empty.',
        ADDRESSEMPTY: 'This field cannot be empty.',
        TOWNCITYEMPTY: 'This field cannot be empty.',
        REGIONEMPTY: 'This field cannot be empty.',
        POSTALCODEEMPTY: 'This field cannot be empty.',
        BUSINESSNAMEEMPTY: 'This field cannot be empty.',
        COMPANYNUMBEREMPTY: 'This field cannot be empty.',
        BUSINESSCATEGORYEMPTY: 'Business category cannot be empty.',
        COMMISSIONEMPTY: '% of admin commission cannot be empty.',
        OTPCODEEMPTY: 'Otp Code cannot be empty.',
        PHONEEMPTY: "This field cannot be empty.",
        PHONEVALID: "Phone number must be between 10-13 digits.",
        MINACCOUNT: "Account number must be 8 digits long.",
        SPECIALCHARNOTVALID: 'This field cannot contain special characters.',
        CUSTOMERNAMEEMPTY: 'Customer name cannot be empty.',
        TRANSACTIONAMOUNTEMPTY: 'Transaction amount can’t be empty.',
        TRANSACTIONAMOUNTINVALID: 'Transaction amount can only contain numerical values.',
        TRANSACTIONDESPEEMPTY: 'Transaction description can’t be empty.',
        INTERIMPAYMENTTITLEEMPTY: ' Interim transaction title  can’t be empty.',
        INTERIMAMOUNTEMPTY: ' Interim amount can’t be empty.',
        INTERIMAMOUNTINVALID: ' Interim amount only contain numeric values',
        SUPPORTEDFILE: "This is not a supported format. Please only upload files in the following formats: JPEG, PNG, PDF.",
        SUPPORTEDFILESIZE: "This is not a supported size. Please upload files between 32KB and 10MB.",
        Invalidamount: "Invalid amount"

    }
}

export default Message