export const LOGIN = "auth/LOGIN";
export const LOGIN_FAILED = "auth/LOGIN_FAILED";
export const LOGIN_COMPLETED = "auth/LOGIN_COMPLETED";

export const AUTHENTICATED = "auth/AUTHENTICATED";
export const AUTHORIZATION_FAILED = "auth/AUTHORIZATION_FAILED";

export const SIGNUP_WITH_EMAIL = "auth/SIGNUP_WITH_EMAIL";
export const SIGNUP_WITH_EMAIL_FAILED = "auth/SIGNUP_WITH_EMAIL_FAILED";
export const SIGNUP_WITH_EMAIL_COMPLETED = "auth/SIGNUP_WITH_EMAIL_COMPLETED";

export const SIGNUP_PROCESS = "auth/SIGNUP_PROCESS";
export const SIGNUP_PROCESS_FAILED = "auth/SIGNUP_PROCESS_FAILED";
export const SIGNUP_PROCESS_COMPLETED = "auth/SIGNUP_PROCESS_COMPLETED";

export const LOGOUT = "auth/LOGOUT";
export const LOGOUT_FAILED = "auth/LOGOUT_FAILED";
export const LOGOUT_COMPLETED = "auth/LOGOUT_COMPLETED";

export const REFRESH_TOKEN = "auth/REFRESH_TOKEN";
export const REFRESH_TOKEN_FAILED = "auth/REFRESH_TOKEN_FAILED";
export const REFRESH_TOKEN_COMPLETED = "auth/REFRESH_TOKEN_COMPLETED";

export const FORGOT_PASSWORD = "auth/FORGOT_PASSWORD";
export const FORGOT_PASSWORD_FAILED = "auth/FORGOT_PASSWORD_FAILED";
export const FORGOT_PASSWORD_COMPLETED = "auth/FORGOT_PASSWORD_COMPLETED";

export const VERIFY_RESET_PASSWORD_LINK = "auth/VERIFY_RESET_PASSWORD_LINK";
export const VERIFY_RESET_PASSWORD_LINK_FAILED = "auth/VERIFY_RESET_PASSWORD_LINK_FAILED";
export const VERIFY_RESET_PASSWORD_LINK_COMPLETED = "auth/VERIFY_RESET_PASSWORD_LINK_COMPLETED";

export const RESET_PASSWORD = "auth/RESET_PASSWORD";
export const RESET_PASSWORD_FAILED = "auth/RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_COMPLETED = "auth/RESET_PASSWORD_COMPLETED";

export const DESTROY = "auth/DESTROY_SESSION";
export const INITIALIZE = "auth/INITIALIZE_SESSION";

export const VERIFY_EMAIL_LINK = "auth/VERIFY_EMAIL_LINK";
export const VERIFY_EMAIL_LINK_FAILED = "auth/VERIFY_EMAIL_LINK_FAILED";
export const VERIFY_EMAIL_LINK_COMPLETED = "auth/VERIFY_EMAIL_LINK_COMPLETED";

export const SET_USER = "SET_USER";

export const IS_USER_REGISTERED = "auth/IS_USER_REGISTERED";
export const IS_USER_REGISTERED_FAILED = "auth/IS_USER_REGISTERED_FAILED";
export const IS_USER_REGISTERED_COMPLETED = "auth/IS_USER_REGISTERED_COMPLETED";

export const LOGIN_WITH_SOCIAL = "auth/LOGIN_WITH_SOCIAL";
export const LOGIN_WITH_SOCIAL_FAILED = "auth/LOGIN_WITH_SOCIAL_FAILED";
export const LOGIN_WITH_SOCIAL_COMPLETED = "auth/LOGIN_WITH_SOCIAL_COMPLETED";

export const CHANGE_PASSWORD = "auth/CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILED = "auth/CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_COMPLETED = "auth/CHANGE_PASSWORD_COMPLETED";

export const UPDATE_COMPANY_INFORMATION = "auth/UPDATE_COMPANY_INFORMATION";
export const UPDATE_COMPANY_INFORMATION_COMPLETED = "auth/UPDATE_COMPANY_INFORMATION_COMPLETED"

export const UBO_DECLARATION = "auth/UBO_DECLARATION";
export const UBO_DECLARATION_COMPLETED = "auth/UBO_DECLARATION_COMPLETED"

export const UPDATE_UBO = "auth/UPDATE_UBO";

export const VERIFY_LOGIN_OTP = "auth/VERIFY_LOGIN_OTP";
export const VERIFY_LOGIN_OTP_FAILED = "auth/VERIFY_LOGIN_OTP_FAILED";
export const VERIFY_LOGIN_OTP_COMPLETED = "auth/VERIFY_LOGIN_OTP_COMPLETED";

export const RESEND_VERIFY_LINK = "auth/RESEND_VERIFY_LINK";
export const RESEND_VERIFY_LINK_FAILED = "auth/RESEND_VERIFY_LINK_FAILED";
export const RESEND_VERIFY_LINK_COMPLETED = "auth/RESEND_VERIFY_LINK_COMPLETED";

export const INVITA_CUSTOMER = "customer/INVITA_CUSTOMER";
export const INVITA_CUSTOMER_FAILED = "customer/INVITA_CUSTOMER_FAILED";
export const INVITA_CUSTOMER_COMPLETED = "customer/INVITA_CUSTOMER_COMPLETED";

