export const LOGIN = "auth/LOGIN";
export const LOGIN_FAILED = "auth/LOGIN_FAILED";
export const LOGIN_COMPLETED = "auth/LOGIN_COMPLETED";

export const GET_INVITED_USERLIST = "GET_INVITED_USERLIST";
export const GET_INVITED_USERLIST_FAILED = "GET_INVITED_USERLIST_FAILED ";
export const GET_INVITED_USERLIST_COMPLETED = "GET_INVITED_USERLIST_COMPLETED";

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_FAILED = "CREATE_JOB_FAILED ";
export const CREATE_JOB_COMPLETED = "CREATE_JOB_COMPLETED";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_FAILED = "GET_USER_DETAILS_FAILED ";
export const GET_USER_DETAILS_COMPLETED = "GET_USER_DETAILS_COMPLETED";

export const CREATE_MILESTONE = "CREATE_MILESTONE";
export const CREATE_MILESTONE_FAILED = "CREATE_MILESTONE_FAILED ";
export const CREATE_MILESTONE_COMPLETED = "CREATE_MILESTONE_COMPLETED";

export const MILESTONE_EMAIL = "MILESTONE_EMAIL";
export const MILESTONE_EMAIL_FAILED = "MILESTONE_EMAIL_FAILED ";
export const MILESTONE_EMAIL_COMPLETED = "MILESTONE_EMAIL_COMPLETED";

export const GET_JOB = "GET_JOB";
export const GET_JOB_FAILED = "GET_JOB_FAILED ";
export const GET_JOB_COMPLETED = "GET_JOB_COMPLETED";

export const GET_INVITED_JOB = "GET_INVITED_JOB";
export const GET_INVITED_JOB_FAILED = "GET_INVITED_JOB_FAILED ";
export const GET_INVITED_JOB_COMPLETED = "GET_INVITED_JOB_COMPLETED";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_FAILED = "GET_CUSTOMER_FAILED ";
export const GET_CUSTOMER_COMPLETED = "GET_CUSTOMER_COMPLETED";

export const UPDATE_CUSTOMER_STATUS = "UPDATE_CUSTOMER_STATUS";
export const UPDATE_CUSTOMER_STATUS_FAILED = "UPDATE_CUSTOMER_STATUS_FAILED ";
export const UPDATE_CUSTOMER_STATUS_COMPLETED = "UPDATE_CUSTOMER_STATUS_COMPLETED";
export const GET_JOB_COUNT = "GET_JOB_COUNT";
export const GET_JOB_COUNT_FAILED = "GET_JOB_COUNT_FAILED ";
export const GET_JOB_COUNT_COMPLETED = "GET_JOB_COUNT_COMPLETED";

export const GET_ONGOING_JOB = "GET_ONGOING_JOB";
export const GET_ONGOING_JOB_FAILED = "GET_ONGOING_JOB_FAILED ";
export const GET_ONGOING_JOB_COMPLETED = "GET_ONGOING_JOB_COMPLETED";

export const ACCEPT_JOB = "ACCEPT_JOB";
export const ACCEPT_JOB_FAILED = "ACCEPT_JOB_FAILED ";
export const ACCEPT_JOB_COMPLETED = "ACCEPT_JOB_COMPLETED";

export const REJECT_JOB = "REJECT_JOB ";
export const REJECT_JOB_FAILED = "REJECT_JOB_FAILED ";
export const REJECT_JOB_COMPLETED = "REJECT_JOB_COMPLETED";

export const DELETE_MILESTONE = "DELETE_MILESTONE ";
export const DELETE_MILESTONE_FAILED = "DELETE_MILESTONE_FAILED ";
export const DELETE_MILESTONE_COMPLETED = "DELETE_MILESTONE_COMPLETED";

export const EDIT_MILESTONE = "EDIT_MILESTONE ";
export const EDIT_MILESTONE_FAILED = "EDIT_MILESTONE_FAILED ";
export const EDIT_MILESTONE_COMPLETED = "EDIT_MILESTONE_COMPLETED";

export const SAVE_JOB = "SAVE_JOB";
export const SAVE_JOB_FAILED = "SAVE_JOB_FAILED ";
export const SAVE_JOB_COMPLETED = "SAVE_JOB_COMPLETED";

export const ESCROW_PAYMENT = "ESCROW_PAYMENT";
export const ESCROW_PAYMENT_FAILED = "ESCROW_PAYMENT_FAILED ";
export const ESCROW_PAYMENT_COMPLETED = "ESCROW_PAYMENT_COMPLETED";


export const CHECK_TRUELAYER_STATUS = "CHECK_TRUELAYER_STATUS";
export const CHECK_TRUELAYER_STATUS_FAILED = "CHECK_TRUELAYER_STATUS_FAILED ";
export const CHECK_TRUELAYER_STATUS_COMPLETED = "CHECK_TRUELAYER_STATUS_COMPLETED";

export const MODIFICATION_REQUEST = "MODIFICATION_REQUEST";
export const MODIFICATION_REQUEST_FAILED = "MODIFICATION_REQUEST_FAILED ";
export const MODIFICATION_REQUEST_COMPLETED = "MODIFICATION_REQUEST_COMPLETED";

export const GET_SUPPORT_AND_TICKET = "GET_SUPPORT_AND_TICKET";
export const GET_SUPPORT_AND_TICKET_FAILED = "GET_SUPPORT_AND_TICKET_FAILED ";
export const GET_SUPPORT_AND_TICKET_COMPLETED = "GET_SUPPORT_AND_TICKET_COMPLETED";

export const SUPPORT_AND_TICKET = "SUPPORT_AND_TICKET";
export const SUPPORT_AND_TICKET_FAILED = "SUPPORT_AND_TICKET_FAILED ";
export const SUPPORT_AND_TICKET_COMPLETED = "SUPPORT_AND_TICKET_COMPLETED";

export const GET_TICKET_DETAILS = "GET_TICKET_DETAILS";
export const GET_TICKET_DETAILS_FAILED = "GET_TICKET_DETAILS_FAILED ";
export const GET_TICKET_DETAILS_COMPLETED = "GET_TICKET_DETAILS_COMPLETED";

export const SUPPORT_AND_TICKET_COMMENT = "SUPPORT_AND_TICKET_COMMENT";
export const SUPPORT_AND_TICKET_COMMENT_FAILED = "SUPPORT_AND_TICKET_COMMENT_FAILED ";
export const SUPPORT_AND_TICKET_COMMENT_COMPLETED = "SUPPORT_AND_TICKET_COMMENT_COMPLETED";

export const SUPPORT_AND_TICKET_RESOLVED = "SUPPORT_AND_TICKET_RESOLVED";
export const SUPPORT_AND_TICKET_RESOLVED_FAILED = "SUPPORT_AND_TICKET_RESOLVED_FAILED ";
export const SUPPORT_AND_TICKET_RESOLVED_COMPLETED = "SUPPORT_AND_TICKET_RESOLVED_COMPLETED";

export const PAYMENT_RELEASE_REQUEST = "PAYMENT_RELEASE_REQUEST";
export const PAYMENT_RELEASE_REQUEST_FAILED = "PAYMENT_RELEASE_REQUEST_FAILED ";
export const PAYMENT_RELEASE_REQUEST_COMPLETED = "PAYMENT_RELEASE_REQUEST_COMPLETED";

export const PAYMENT_RELEASE = "PAYMENT_RELEASE";
export const PAYMENT_RELEASE_FAILED = "PAYMENT_RELEASE_FAILED ";
export const PAYMENT_RELEASE_COMPLETED = "PAYMENT_RELEASE_COMPLETED";

export const DISPUTE_REISED = "DISPUTE_REISED";
export const DISPUTE_REISED_FAILED = "DISPUTE_REISED_FAILED ";
export const DISPUTE_REISED_COMPLETED = "DISPUTE_REISED_COMPLETED";

export const GET_DISPUTE_REISED = "GET_DISPUTE_REISED";
export const GET_DISPUTE_REISED_FAILED = "GET_DISPUTE_REISED_FAILED ";
export const GET_DISPUTE_REISED_COMPLETED = "GET_DISPUTE_REISED_COMPLETED";

export const GET_DISPUTE_REISED_DETAILS = "GET_DISPUTE_REISED_DETAILS";
export const GET_DISPUTE_REISED_DETAILS_FAILED = "GET_DISPUTE_REISED_DETAILS_FAILED ";
export const GET_DISPUTE_REISED_DETAILS_COMPLETED = "GET_DISPUTE_REISED_DETAILS_COMPLETED";

export const ANNOUNCE_DETAILS = "ANNOUNCE_DETAILS";
export const ANNOUNCE_DETAILS_FAILED = "ANNOUNCE_DETAILS_FAILED ";
export const ANNOUNCE_DETAILS_COMPLETED = "ANNOUNCE_DETAILS_COMPLETED";

export const RISED_DISPUTE_RESULT = "RISED_DISPUTE_RESULT";
export const RISED_DISPUTE_RESULT_FAILED = "RISED_DISPUTE_RESULT_FAILED ";
export const RISED_DISPUTE_RESULT_COMPLETED = "RISED_DISPUTE_RESULT_COMPLETED";

export const CREATE_CHANNEL_ID = "CREATE_CHANNEL_ID";
export const CREATE_CHANNEL_ID_FAILED = "CREATE_CHANNEL_ID_FAILED ";
export const CREATE_CHANNEL_ID_COMPLETED = "CREATE_CHANNEL_ID_COMPLETED";

export const ADD_STAFF_MEMBER = "ADD_STAFF_MEMBER";
export const ADD_STAFF_MEMBER_FAILED = "ADD_STAFF_MEMBER_FAILED ";
export const ADD_STAFF_MEMBER_COMPLETED = "ADD_STAFF_MEMBER_COMPLETED";

export const GET_STAFF_MEMBER = "GET_STAFF_MEMBER";
export const GET_STAFF_MEMBER_FAILED = "GET_STAFF_MEMBER_FAILED ";
export const GET_STAFF_MEMBER_COMPLETED = "GET_STAFF_MEMBER_COMPLETED";

export const DELETE_STAFF_MEMBER = "DELETE_STAFF_MEMBER";
export const DELETE_STAFF_MEMBER_FAILED = "DELETE_STAFF_MEMBER_FAILED ";
export const DELETE_STAFF_MEMBER_COMPLETED = "DELETE_STAFF_MEMBER_COMPLETED";

export const EDIT_STAFF_MEMBER = "EDIT_STAFF_MEMBER";
export const EDIT_STAFF_MEMBER_FAILED = "EDIT_STAFF_MEMBER_FAILED ";
export const EDIT_STAFF_MEMBER_COMPLETED = "EDIT_STAFF_MEMBER_COMPLETED";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED ";
export const EDIT_PROFILE_COMPLETED = "EDIT_PROFILE_COMPLETED";

export const GET_PAYMENT_HISTORY = "GET_PAYMENT_HISTORY";
export const GET_PAYMENT_HISTORY_FAILED = "GET_PAYMENT_HISTORY_FAILED ";
export const GET_PAYMENT_HISTORY_COMPLETED = "GET_PAYMENT_HISTORY_COMPLETED";

export const GET_KYC_STATUS = "GET_KYC_STATUS";
export const GET_KYC_STATUS_FAILED = "GET_KYC_STATUS_FAILED ";
export const GET_KYC_STATUS_COMPLETED = "GET_KYC_STATUS_COMPLETED";

export const GET_COMMISSION = "GET_COMMISSION";
export const GET_COMMISSION_FAILED = "GET_COMMISSION_FAILED ";
export const GET_COMMISSION_COMPLETED = "GET_COMMISSION_COMPLETED";